spring.application.name=chatapp
spring.datasource.url=jdbc:mysql://localhost:3306/chatapp
spring.datasource.username=root
spring.datasource.password=Ha1lhydra
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

translator.api.url=https://unparticipated-lecia-forcefully.ngrok-free.dev
# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=md.haaroon0710@gmail.com
spring.mail.password=sqix orkc mdkz yfnn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cloudinary
cloudinary.cloud-name=dgxzjax8b
cloudinary.api-key= 838949268952662
cloudinary.api-secret=Z_OG3n3uUEyi2e8DguD7_8Hv0oU

# OTP expiry in minutes
otp.expiry.minutes=10

spring.websocket.enabled=true
